Feature: Conference word cloud
	Once clicking on a conference name, a new list is generated 

	Scenario: Paper should contain the following titles
		Given I click on the first conference from the list for term and Bengio
		Then I should be on the word cloud for IEEE Transactions

	Scenario: Fixing bug with word cloud generated by conference 
		Given I click on the first conference from the list for across and Lee
		And I click on the word second
		Then I should be on a populated paper list page 
